### ISSUE TITLE
images

### ISSUE THREAD

**Issue by axlroden** [gkpln3/ConfluenceToWikiJS#1]
What about images? Does not seem to come over.

**Comment by gkpln3** [comment]
You can copy the images straight into the wikijs data directory, it should link them properly.

**Comment by axlroden** [comment]
yea, I could see in the source of the pages it looked fairly straight forward :)

**Comment by GunArm** [comment]
Where is the "wikijs data directory"?  I am running a test instance of wikijs I made quickly using your provided docker-compose file (thanks!), is that some directory inside the wikijs container that I need to expose to the host with a bind mount?  I'm actually surprised to hear there is a data directory since I assumed all of that went into postgres.

**Comment by axlroden** [comment]
> Where is the "wikijs data directory"? I am running a test instance of wikijs I made quickly using your provided docker-compose file (thanks!), is that some directory inside the wikijs container that I need to expose to the host with a bind mount? I'm actually surprised to hear there is a data directory since I assumed all of that went into postgres.

You should create a new issue, this one is closed and not related to your question.

**Comment by gkpln3** [comment]
@GunArm Please create a separate issue next time.
You can set a data directory through the wiki-js configuration interface, then map the same directory using the `docker-compose.yml` file.
